import { pgTable, text, serial, integer, timestamp, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const studySessions = pgTable("study_sessions", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  topic: text("topic").notNull(),
  originalContent: text("original_content").notNull(),
  summary: text("summary").notNull(),
  keyPoints: jsonb("key_points").$type<string[]>().notNull(),
  quizQuestions: jsonb("quiz_questions").$type<{ question: string; options: string[]; answer: string }[]>().notNull(),
  difficulty: integer("difficulty").notNull().default(3), // 1-5 rating
  createdAt: timestamp("created_at").defaultNow(),
});

export const conceptExplanations = pgTable("concept_explanations", {
  id: serial("id").primaryKey(),
  term: text("term").notNull(),
  explanation: text("explanation").notNull(),
  analogy: text("analogy").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertStudySessionSchema = createInsertSchema(studySessions).omit({ 
  id: true, 
  createdAt: true,
  summary: true, // Generated by backend
  keyPoints: true, // Generated by backend
  quizQuestions: true // Generated by backend
});

export const insertConceptExplanationSchema = createInsertSchema(conceptExplanations).omit({
  id: true,
  createdAt: true,
  explanation: true, // Generated by backend
  analogy: true // Generated by backend
});

export type StudySession = typeof studySessions.$inferSelect;
export type InsertStudySession = z.infer<typeof insertStudySessionSchema>;

export type ConceptExplanation = typeof conceptExplanations.$inferSelect;
export type InsertConceptExplanation = z.infer<typeof insertConceptExplanationSchema>;
